import Link from "next/link"

export const metadata = {
  title: "Terms of Service | DevTools",
  description: "Terms of service for DevTools AI-powered tools",
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto pt-8">
      <Link
        href="/"
        className="inline-flex items-center px-4 py-2 mb-8 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors duration-200"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="h-5 w-5 mr-2"
          viewBox="0 0 20 20"
          fill="currentColor"
        >
          <path
            fillRule="evenodd"
            d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z"
            clipRule="evenodd"
          />
        </svg>
        Back to Home
      </Link>

      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="mb-4">
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and
        use of DevTools&apos; AI-powered tools and services. By accessing or
        using our services, you agree to be bound by these Terms.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">
        Disclaimer of Liability
      </h2>
      <p className="mb-4">
        Our AI-powered tools are provided &ldquo;as is&rdquo; and &ldquo;as
        available&rdquo; without any warranties, express or implied. We do not
        guarantee the accuracy, completeness, or reliability of any results or
        output generated by our AI tools. You acknowledge and agree that your
        use of our services is at your own risk.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">
        Limitation of Liability
      </h2>
      <p className="mb-4">
        To the fullest extent permitted by law, DevTools shall not be liable for
        any indirect, incidental, special, consequential, or punitive damages,
        or any loss of profits or revenues, whether incurred directly or
        indirectly, or any loss of data, use, goodwill, or other intangible
        losses resulting from your access to or use of our AI-powered tools.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">
        User Responsibilities
      </h2>
      <p className="mb-4">
        You are solely responsible for any content you input into our AI tools
        and for how you use the output. You agree not to use our services for
        any illegal or unauthorized purpose and to comply with all applicable
        laws and regulations.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">
        Intellectual Property
      </h2>
      <p className="mb-4">
        You retain ownership of any intellectual property rights in the content
        you input into our AI tools. However, by using our services, you grant
        DevTools a worldwide, non-exclusive, royalty-free license to use,
        reproduce, and distribute the output generated by our AI tools for the
        purposes of providing and improving our services.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">
        Modifications to Service
      </h2>
      <p className="mb-4">
        We reserve the right to modify or discontinue, temporarily or
        permanently, our services with or without notice. We shall not be liable
        to you or any third party for any modification, suspension, or
        discontinuance of the service.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Governing Law</h2>
      <p className="mb-4">
        These Terms shall be governed by and construed in accordance with the
        laws of Turkey, without regard to its conflict of law provisions.
      </p>
    </div>
  )
}
